### PR TITLE
Treat rating_text as optional value

### PR DESCRIPTION
**Pull request by sunshinedaniel**
This PR makes the SDK treat `rating_text` of Hotel Details as optional value.

### CODE REVIEW

**Comment by Kingson-de** [comment]
What is the benefit of this change?
Before it was type safe, now you always need to do a null check if you are going to use it.
If you just wanna know if it set, then you can use *!empty* in your application.

**Comment by Kingson-de** [comment]
@sunshinedaniel Please use the isset but always provide a string. So if it is not set, we are using an empty string.

**Comment by sunshinedaniel** [comment]
Thanks for the feedback. I'm happy to do that. This is actually how I first implemented it, but saw that other fields like `homepage` can return `null` and tried to have a consistent behavior . But I also prefer the empty string fallback and will implement this.

**Comment by Kingson-de** [comment]
Good point with homepage, we should change it :) Thank you for your contribution!

**Pull request merged**
